spring:
  application:
    name: dnd-travel-project
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update # local에서만 사용할거고, prod 환경과 분리 필요
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO  # 로그 레벨 설정

social-login:
  provider:
    apple:
      grant-type: authorization_code
      client-id: ${APPLE_CLIENT_ID}
      key-id: ${APPLE_KEY_ID} # 애플에서 제공하는 키의 ID
      team-id: ${APPLE_TEAM_ID} # 애플 개발자 계정의 팀 ID
      audience: https://appleid.apple.com
      private-key: ${APPLE_PRIVATE_KEY}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expired-ms: ${ACCESS_TOKEN_EXPIRE_DEV}
  refresh-token-expired-ms: ${REFRESH_TOKEN_EXPIRE_DEV}

cloud:
  aws:
    credentials:
      accessKey: ${EC2_ACCESS_KEY_DEV}
      secretKey: ${EC2_SECRET_KEY_DEV}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucketName: ${AWS_BUCKET_NAME_DEV}

